export const posts = [
  {
    slug: 'best-dentist-in-kolkata-2025-guide',
    title: 'Best Dentist in Kolkata: 2025 Guide to Choosing the Right Clinic',
    category: 'Guides',
    date: '2025-01-05',
    excerpt: 'Looking for the best dentist in Kolkata? Compare treatments, costs, and technology in this 2025 guide.',
    keywords: ['best dentist kolkata', 'dental clinic kolkata', 'dentist near me'],
    cover: 'https://images.unsplash.com/photo-1629909613638-0e4a1fad8f81',
    content: `Choosing a dental clinic in Kolkata can be overwhelming. In this guide, we compare technology (digital X-rays, rotary endo), common treatments (RCT, implants, braces), emergency availability, and cost transparency. Learn how Dent O Dent provides painless treatments with experienced specialists.`,
  },
  {
    slug: 'root-canal-cost-in-kolkata-painless-options',
    title: 'Root Canal Cost in Kolkata: Painless Options Explained',
    category: 'Endodontics',
    date: '2025-01-12',
    excerpt: 'Understand pain-free RCT options, typical prices, and same-day emergency treatment availability in Kolkata.',
    keywords: ['root canal kolkata', 'rct cost kolkata', 'painless root canal'],
    cover: 'https://images.unsplash.com/photo-1588776814546-1ff441c36edb',
    content: `Root canal therapy at Dent O Dent uses rotary endodontics and apex locators for precise and comfortable procedures. Typical pricing depends on tooth location and severity. We offer transparent estimates and EMI plans.`,
  },
  {
    slug: 'dental-implants-vs-bridges-kolkata',
    title: 'Dental Implants vs Bridges in Kolkata: What’s Better for You?',
    category: 'Implants',
    date: '2025-01-20',
    excerpt: 'Compare durability, aesthetics, maintenance, and long-term costs for implants and bridges in Kolkata.',
    keywords: ['dental implants kolkata', 'teeth replacement kolkata', 'bridge vs implant'],
    cover: 'https://images.unsplash.com/photo-1606811842058-3c80e8d78af2',
    content: `Dental implants offer a permanent tooth replacement solution with superior function and aesthetics. Bridges can be suitable in specific cases. We evaluate bone density, adjacent teeth, and hygiene to recommend the best option.`,
  },
  {
    slug: 'braces-or-aligners-kolkata-which-is-right',
    title: 'Braces or Aligners in Kolkata: Which Is Right for You?',
    category: 'Orthodontics',
    date: '2025-01-26',
    excerpt: 'Learn the pros and cons of metal, ceramic braces, and clear aligners with timelines and pricing.',
    keywords: ['braces kolkata', 'aligners kolkata', 'orthodontist kolkata'],
    cover: 'https://images.unsplash.com/photo-1586089209857-6621e1d61b78',
    content: `Metal and ceramic braces are effective for complex cases. Clear aligners provide an aesthetic, removable option for mild to moderate corrections. We provide digital scans and treatment simulations to help you decide.`,
  },
  {
    slug: 'teeth-whitening-safe-methods-kolkata',
    title: 'Safe Teeth Whitening in Kolkata: Methods, Safety, and Results',
    category: 'Cosmetic',
    date: '2025-02-01',
    excerpt: 'Discover in-clinic laser whitening and take-home kits with safety tips and realistic expectations.',
    keywords: ['teeth whitening kolkata', 'laser whitening kolkata', 'cosmetic dentistry kolkata'],
    cover: 'https://images.unsplash.com/photo-1581089781785-04049cb29d0f',
    content: `We use clinically approved whitening systems for safe, immediate results. Sensitivity management and maintenance routines help sustain brightness.`,
  },
];